#!/bin/bash

# Wrapper script to facilitate running lrose commands in a container.
# Bruno Melli 4/7/18
#
# Basically, instead of doing something like this:
# docker run <bunch of docker options> /usr/local/lrose/bin/<cmd> <cmd options>
# You do
# lrose <few options listed below> -- <cmd> <cmd options>
#
# By default, the image is lrose-blaze and the container is lrose-container

print_help() {
    echo "usage: lrose [args] -- command [command args]"
    cat <<EOF

    -a|--argfile <file>		Specify a file that has additional volume mappings
    		 			By default it uses ~/.lroseargs
					See -v option. One entry per line: from:to
    -h|--help			Print help and exit 
    -c|--container <name>	Use this container instead of the default lrose-container 
    -d|--debug			Print debug info 
    -i|--image <name>		Use this image instead of the default lrose-image 
    -n|--no			Don't run the command (useful with -d) 
    -r|--remove			Remove the container when done 
    -v|--volume <from:to>	Add volume mappings. You can have several -v options 
    				    from is your local host absolute path 
				    to is the absolute path inside the container.
EOF
}

# Run a command... or not.

run_cmd() {
    verbose=$1
    shift
    run=$1
    shift
    cmd="$1"
    shift
    if [ "$verbose" -eq 1 ]; then
	echo "cmd: $cmd $@"
    fi

    if [ "$run" -eq 1 ]; then
	result="$($cmd "$@")"
	echo "$result"
    fi
}

# Print a message if debug is set to 1

print_msg() {
    debug=$1
    shift
    if [ "$debug" -eq 1 ]; then
	echo "$@"
    fi
}

# Set the variable whose name was given in $2 to the status of container $1

container_status() {
    local result=$2
    local entry=`docker ps -a --filter "name=$1" --format "{{.ID}}:{{.Status}}"`
    eval $result="'$entry'"
}

# A few default values that can be overwritten on the command line

REMOVE="--rm"
IMAGE="lrose-blaze-040318"
CONTAINER="lrose-container"
ARG_FILE="$HOME/.lroseargs"
VOLUME_ARGS=""

debug=0
run_flag=1

# Common docker options

my_os=`uname`
case $my_os in
    Linux)
	DISPLAY_OPT="--env=\"DISPLAY\" --env QT_X11_NO_MITSHM=1"
	;;	
    Darwin)
	my_host=`hostname`
	my_ip=`host $my_host`
	my_ip=${my_ip##* }
	DISPLAY_OPT="-e DISPLAY=$my_ip:0"
    ;;
    *)
	echo "Unknown OS '$my_os'. I don't know how to set up DISPLAY. Using Linux"
	DISPLAY_OPT="--env=\"DISPLAY\" --env QT_X11_NO_MITSHM=1"
	;;
esac

# Process options

while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
	-a|--argfile)
	    ARG_FILE="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-h|--help)
	    print_help
	    exit 0
	    ;;
	-c|--container)
	    CONTAINER="$2"
	    shift
	    shift
	    ;;
	-d|--debug)
	    debug=1
	    shift
	    ;;
	-i|--image)
	    IMAGE="$2"
	    shift # past argument
	    shift # past value
	    ;;
	-n|--no)
	    run_flag=0
	    shift
	    ;;
	-r|--rm)
	    REMOVE="--rm"
	    shift # past argument
	    ;;
	-v|--volume)
	    VOLUME_ARGS="VOLUME_ARGS -v $2"
	    shift # past argument
	    shift # past value
	    ;;
	--)
	    shift # past --
	    break
	    ;;
	*)    # unknown option
	    echo "Unknown option '$key' (Did you forget the --)"
	    print_help
	    exit 1
	    ;;
    esac
done

# Whatever is left is the lrose command to run
# Prepend path to lrose bin directory if path is not specified.
# TODO: just add /usr/local/lrose/bin to PATH when building the image?

command=$1
shift
if [[ ! "$command" == *\/* ]]; then
    command="/usr/local/lrose/bin/$command"
fi

# Load user specified volume options

if [[ -r "$ARG_FILE" ]]; then
    while read -r line
    do
	if [[ ! $line = $'#'* ]]; then	# skip comments
	    VOLUME_ARGS="$VOLUME_ARGS -v $line"
	fi
    done < $ARG_FILE
else
    echo "$ARG_FILE not readable"
fi

# Some debug stuff

if [ "$debug" -eq 1 ]; then
    echo "image: $IMAGE"
    echo "container: $CONTAINER"
    echo "REMOVE: $REMOVE"
    echo "ARG_FILE: $ARG_FILE"
    echo "VOLUME_ARGS: $VOLUME_ARGS"
    echo "command invocation: $command $@"
fi

# Get the status of the lrose_container.

container_status "$CONTAINER" status
print_msg $debug "status: $status"

cid="${status%:*}"	 # everything before the :
cstatus="${status##*:}"  # everything after the :
cstatus="${cstatus%% *}" # Only keep the first word

print_msg $debug "id: '$cid', status: '$cstatus'"

# Set up some docker options for the different state the container could be in

docker_display_opts="$DISPLAY_OPT -v /tmp/.X11-unix:/tmp/.X11-unix:rw"
docker_run_opts="-t --name $CONTAINER --user lrose -w /home/lrose"
docker_exec_opts="-t --user lrose -w /home/lrose"

docker_volume_opts=""

# Run the command in a container.

case "$cstatus" in
    Up)
	print_msg $debug "Container is up and running"
	run_cmd $debug $run_flag docker exec $docker_exec_opts $CONTAINER $command "$@"
	;;
    Exited)
	print_msg $debug "Container exited. Restarting it"
	run_cmd $debug $run_flag docker start "$CONTAINER"
	run_cmd $debug $run_flag docker exec $docker_exec_opts $CONTAINER $command "$@"
	;;
    *)
	if [ ! -z "$cstatus" ]; then
	    echo "Container '$CONTAINER' status not recognized '$cstatus'"
	    exit 1
	fi
	print_msg $debug "Container doesn't exist. Starting one"
	 run_cmd $debug $run_flag \
		 docker run $REMOVE $VOLUME_ARGS $docker_display_opts \
		 $docker_run_opts $IMAGE $command "$@"
	;;
esac

exit 0
